import type { Metadata } from "next";
import { CalendarDays, Mail, MapPin, MessageCircle } from "lucide-react";
import EnquiryForm from "@/components/EnquiryForm";
import { Container, PageIntro } from "@/components/ui";
import { site } from "@/lib/content";
import { createMetadata } from "@/lib/seo";
export const metadata:Metadata=createMetadata("Contact","Talk to VertexIQ Systems about websites, business systems, software products, mobile apps, automation or integrations.","/contact");
const contacts=[{title:"Email",value:site.email,href:`mailto:${site.email}`,icon:Mail},{title:"WhatsApp UK",value:"+44 7376 174981",href:site.ukWhatsapp,icon:MessageCircle},{title:"WhatsApp Ghana",value:"+233 534 177 839",href:site.ghWhatsapp,icon:MessageCircle},{title:"Book a call",value:"Free strategy consultation",href:site.calendlyUrl,icon:CalendarDays}];
export default function Page(){return <><PageIntro eyebrow="Contact" title="Tell us what you want your technology to do better." description="Share the business challenge, current workflow or product idea. We will review the context and respond with a useful next step."/><section className="py-16 sm:py-20"><Container><div className="grid gap-10 lg:grid-cols-[1.18fr_.82fr]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5 sm:p-8"><h2 className="text-2xl font-semibold text-white">Start a project conversation</h2><p className="mt-3 leading-7 text-slate-400">You do not need a finished brief. Fields marked with an asterisk are required.</p><div className="mt-8"><EnquiryForm/></div></div><aside className="space-y-5 lg:sticky lg:top-28 lg:self-start" aria-label="Direct contact options"><div className="card"><h2 className="text-xl font-semibold text-white">Contact VertexIQ directly</h2><div className="mt-6 grid gap-3">{contacts.map(x=>{const Icon=x.icon;return <a key={x.title} href={x.href} target={x.href.startsWith("http")?"_blank":undefined} rel={x.href.startsWith("http")?"noreferrer":undefined} className="flex min-h-16 items-center gap-4 rounded-xl border border-white/8 p-4 hover:border-cyan-200/20"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-cyan-300/10 text-cyan-200"><Icon aria-hidden="true" size={18}/></span><span className="min-w-0"><span className="block text-xs text-slate-500">{x.title}</span><span className="mt-1 block break-words text-sm font-semibold text-white">{x.value}</span></span></a>})}</div></div><div className="card"><div className="flex gap-3"><MapPin aria-hidden="true" className="mt-1 shrink-0 text-cyan-200" size={18}/><div><h2 className="font-semibold text-white">Delivery presence</h2><p className="mt-3 leading-7 text-slate-400">Ghana<br/>United Kingdom<br/>Global remote delivery</p></div></div></div></aside></div></Container></section></>}
