import type { Metadata } from "next";
import { Globe2, MapPin } from "lucide-react";
import { createMetadata } from "@/lib/seo";
import { ButtonLink, Container, CTA, PageIntro, SectionHeading } from "@/components/ui";
export const metadata:Metadata=createMetadata("Locations & Delivery","VertexIQ Systems works across Ghana and the United Kingdom, with remote delivery for suitable projects elsewhere.","/locations");
const regions=[
  {name:"Ghana",label:"Business presence",text:"VertexIQ works with Ghanaian businesses and is developing technology for local operating contexts, including Fields OS and MedLink.",icon:MapPin},
  {name:"United Kingdom",label:"Business presence",text:"VertexIQ supports UK business and product-engineering work, including the MOTIX implementation connected to ATECH Services UK.",icon:MapPin},
  {name:"Global delivery",label:"Remote collaboration",text:"Suitable website, software and systems work can be delivered through structured remote discovery, review and project collaboration.",icon:Globe2},
];
export default function Page(){return <><PageIntro eyebrow="Locations & delivery" title="Grounded in Ghana and the United Kingdom. Built for connected delivery." description="VertexIQ combines regional business context with structured remote product and software engineering." actions={<ButtonLink href="/contact">Discuss a project</ButtonLink>}/><section className="py-20"><Container><SectionHeading eyebrow="Where we work" title="Regional context with structured global delivery" description="VertexIQ combines business presence in Ghana and the United Kingdom with remote collaboration for suitable projects worldwide."/><div className="mt-10 grid gap-5 lg:grid-cols-3">{regions.map(region=>{const Icon=region.icon;return <article className="card" key={region.name}><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200"><Icon aria-hidden="true" size={20}/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-slate-500">{region.label}</p><h2 className="mt-3 text-2xl font-semibold text-white">{region.name}</h2><p className="mt-4 leading-7 text-slate-400">{region.text}</p></article>})}</div></Container></section><CTA title="Wherever the project starts, begin with the business need."/></>}
