import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Blocks, Bot, ChartNoAxesCombined, Lightbulb, Network, Settings2 } from "lucide-react";
import { industries, implementations, products, solutions } from "@/lib/content";
import { createMetadata } from "@/lib/seo";
import { ButtonLink, CardLink, Container, CTA, Eyebrow, SectionHeading, StatusBadge } from "@/components/ui";

export const metadata: Metadata=createMetadata("Technology That Helps Businesses Grow — And Run Better","Websites, business systems, software platforms, mobile apps and AI automation designed around how businesses actually work.","/");

const problems=[
  {title:"I need more customers",description:"Strengthen how people discover, understand and contact your business.",href:"/solutions/websites-digital-growth",icon:ChartNoAxesCombined},
  {title:"Too much of our work is manual",description:"Turn repetitive administration into clearer, connected workflows.",href:"/solutions/crm-business-systems",icon:Settings2},
  {title:"Our systems don’t work together",description:"Connect essential tools and reduce duplicated work.",href:"/solutions/systems-integration",icon:Network},
  {title:"I have an idea I want to build",description:"Shape a focused software product or custom platform.",href:"/solutions/custom-software",icon:Lightbulb},
];
const buildPaths=[
  ["A website that generates enquiries","/solutions/websites-digital-growth"],
  ["A customer, booking or CRM system","/solutions/crm-business-systems"],
  ["A mobile application","/solutions/mobile-applications"],
  ["Automation for repetitive work","/solutions/ai-automation"],
  ["Connected existing systems","/solutions/systems-integration"],
  ["A custom software or SaaS idea","/solutions/custom-software"],
] as const;

export default function HomePage(){return <>
  <section className="hero-shell"><Container className="relative py-16 sm:py-20 lg:py-24"><div className="grid gap-10 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div><Eyebrow>Product engineering · Business technology</Eyebrow><h1 className="display-title mt-6">Technology That Helps Businesses Grow — And Run Better.</h1><p className="lead mt-6 max-w-3xl">Websites, business systems, software platforms, mobile apps and AI automation designed around the way businesses actually work.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/business-technology-review">Get your free business technology review</ButtonLink><ButtonLink href="/our-work" variant="secondary">Explore our work</ButtonLink></div></div><div className="relative rounded-[1.5rem] border border-white/10 bg-white/[.035] p-4 sm:p-5"><div className="rounded-2xl border border-cyan-200/10 bg-[#081421] p-5 sm:p-6"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-300">VertexIQ technology portfolio</p><span className="h-2 w-2 rounded-full bg-emerald-300"/></div><div className="mt-6 grid grid-cols-2 gap-3">{products.map(x=><Link key={x.id} href={`/products/${x.slug}`} className="rounded-xl border border-white/8 bg-white/[.035] p-3.5 hover:border-cyan-200/25"><p className="text-sm font-semibold text-white">{x.name}</p><p className="mt-2 text-xs text-slate-500">{x.sector}</p></Link>)}</div><div className="mt-4 flex items-center gap-3 rounded-xl bg-cyan-300/8 p-3.5 text-sm text-cyan-100"><Blocks aria-hidden="true" size={18}/>Technology built by VertexIQ.</div></div></div></div></Container></section>
  <section aria-label="Capability and proof" className="border-b border-white/8"><Container><ul className="grid grid-cols-2 py-4 text-center text-[11px] font-bold uppercase tracking-[.12em] text-slate-400 sm:grid-cols-3 lg:grid-cols-6">{["Websites","Business Systems","SaaS","Mobile Apps","AI & Automation","Integrations"].map(x=><li className="py-2" key={x}>{x}</li>)}</ul><div className="flex flex-wrap items-center justify-center gap-x-5 gap-y-2 border-t border-white/8 py-4 text-xs text-slate-500"><span className="font-semibold text-slate-300">Real products and implementations:</span>{["MOTIX™","Fields OS™","MedLink","XMOR Care OS™","ATECH Services UK","EcoClean Ghana"].map(x=><span key={x}>{x}</span>)}</div></Container></section>
  <section className="py-20 sm:py-24"><Container><SectionHeading eyebrow="Start with the problem" title="What is holding your business back?" description="You do not need to arrive with a technical specification. Start with the part of the business that is not working well enough."/><div className="mt-10 grid gap-5 md:grid-cols-2">{problems.map(x=>{const Icon=x.icon;return <Link className="card group flex gap-5" href={x.href} key={x.title}><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200"><Icon aria-hidden="true"/></span><span><span className="text-lg font-semibold text-white">{x.title}</span><span className="mt-2 block leading-7 text-slate-400">{x.description}</span><span className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-cyan-200">Find a path forward <ArrowRight aria-hidden="true" size={15}/></span></span></Link>})}</div></Container></section>
  <section className="border-y border-white/8 bg-white/[.02] py-16"><Container><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><SectionHeading eyebrow="Choose by solution" title="What can we build for you?" description="Know the type of technology you need? Go straight to the most relevant capability."/><div className="grid gap-3 sm:grid-cols-2">{buildPaths.map(([label,href])=><Link key={href} href={href} className="flex min-h-16 items-center justify-between rounded-xl border border-white/8 bg-[#07101b] px-4 py-3 text-sm font-semibold text-slate-200 hover:border-cyan-200/25 hover:text-cyan-100">{label}<ArrowRight aria-hidden="true" size={15}/></Link>)}<Link href="/business-technology-review" className="flex min-h-16 items-center justify-between rounded-xl border border-cyan-200/20 bg-cyan-300/8 px-4 py-3 text-sm font-semibold text-cyan-100 sm:col-span-2">Not sure — review my business<ArrowRight aria-hidden="true" size={15}/></Link></div></div></Container></section>
  <section className="py-20"><Container><SectionHeading eyebrow="Solutions" title="One partner across customer growth and operations"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{solutions.slice(0,6).map(x=><CardLink key={x.slug} href={`/solutions/${x.slug}`} title={x.name} description={x.summary}/>)}</div><div className="mt-8"><ButtonLink href="/solutions" variant="secondary">Explore all solutions</ButtonLink></div></Container></section>
  <section className="py-20 sm:py-24"><Container><SectionHeading eyebrow="Technology by VertexIQ" title="Platforms built from operational experience" description="Our product portfolio turns sector-specific workflows into clearer, connected technology."/><div className="mt-10 grid gap-5 lg:grid-cols-2">{products.map(x=><Link href={`/products/${x.slug}`} className="card group" key={x.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-slate-500">{x.sector}</p><h3 className="mt-2 text-2xl font-semibold text-white">{x.name}</h3></div><StatusBadge label={x.status} tone={x.statusTone}/></div><p className="mt-5 leading-7 text-slate-400">{x.summary}</p><p className="mt-7 text-sm font-semibold text-cyan-200">Explore {x.name} →</p></Link>)}</div></Container></section>
  <section className="border-y border-white/8 bg-white/[.02] py-20"><Container><SectionHeading eyebrow="Client implementations" title="Technology connected to real work" description="Verified client relationships, presented separately from VertexIQ-owned products."/><div className="mt-10 grid gap-5 md:grid-cols-2">{implementations.map(x=><CardLink key={x.id} href={`/our-work/${x.slug}`} eyebrow={x.sector} title={x.client} description={x.summary}/>)}</div></Container></section>
  <section className="py-20"><Container><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Industries" title="Understand the operation before choosing the technology"/><div className="grid gap-3 sm:grid-cols-2">{industries.map(x=><Link key={x.slug} className="flex items-center justify-between rounded-xl border border-white/8 p-4 text-sm font-semibold text-slate-200 hover:border-cyan-200/25 hover:text-cyan-100" href={`/industries/${x.slug}`}>{x.name}<ArrowRight aria-hidden="true" size={15}/></Link>)}</div></div></Container></section>
  <section className="border-y border-white/8 bg-white/[.02] py-20"><Container><div className="grid gap-8 md:grid-cols-3"><Value icon={Lightbulb} title="Business-first" text="We begin with the operating problem, customer journey and commercial context."/><Value icon={Blocks} title="Product-minded" text="We design coherent systems that can be maintained and improved, not isolated screens."/><Value icon={Bot} title="Appropriately ambitious" text="We use automation and modern engineering where they create meaningful value."/></div><div className="mt-10 flex flex-wrap gap-3"><ButtonLink href="/why-us" variant="secondary">Why VertexIQ</ButtonLink><ButtonLink href="/how-we-work" variant="quiet">See how we work</ButtonLink></div></Container></section>
  <section className="py-20"><Container><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{["Discover","Design","Build","Launch","Improve"].map((x,i)=><div className="card" key={x}><p className="text-xs font-bold text-cyan-200">0{i+1}</p><p className="mt-4 text-lg font-semibold text-white">{x}</p></div>)}</div></Container></section>
  <section className="border-y border-white/8 bg-[#07111d] py-20"><Container><div className="grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><SectionHeading eyebrow="Innovation" title="Building technology for focused verticals" description="MOTIX, Fields OS, MedLink and XMOR Care OS reflect a long-term commitment to product engineering. Each product is presented with its current, approved status."/><div className="lg:text-right"><ButtonLink href="/products">Explore the portfolio</ButtonLink></div></div></Container></section>
  <CTA/>
 </>}

function Value({icon:Icon,title,text}:{icon:typeof Blocks;title:string;text:string}){return <div><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200"><Icon aria-hidden="true" size={21}/></span><h3 className="mt-5 text-xl font-semibold text-white">{title}</h3><p className="mt-3 leading-7 text-slate-400">{text}</p></div>}
