import Link from "next/link";
import Image from "next/image";
import { ArrowRight } from "lucide-react";
import { industries, industryBySlug, implementationById, productById, solutionBySlug, type Industry, type Implementation, type Product, type Solution } from "@/lib/content";
import { Breadcrumbs, ButtonLink, CardLink, Checklist, Container, CTA, PageIntro, ProductVisual, SectionHeading, StatusBadge } from "./ui";
import MotixLiveWorkshopDemo from "./MotixLiveWorkshopDemo";
import { MotixCrossDeviceStory, MotixFrontDoorStory } from "./MotixConnectedGarageStory";

export function SolutionPage({ solution }: { solution: Solution }) {
  const relatedIndustries = solution.industrySlugs.map(industryBySlug).filter(Boolean) as Industry[];
  const relatedProducts = (solution.productIds ?? []).map(productById).filter(Boolean) as Product[];
  return <>
    <PageIntro eyebrow={solution.eyebrow} title={solution.name} description={solution.summary} breadcrumbs={[{label:"Solutions",href:"/solutions"},{label:solution.name}]} actions={<><ButtonLink href="/business-technology-review">Discuss your business</ButtonLink><ButtonLink href="/how-we-work" variant="secondary">How we work</ButtonLink></>}/>
    <section className="py-20 sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><SectionHeading eyebrow="The business problem" title={solution.problem}/><div className="grid gap-6 sm:grid-cols-2"><InfoBlock title="Who it is for" items={solution.audience}/><InfoBlock title="What we can build" items={solution.builds}/></div></div></Container></section>
    <section className="border-y border-white/8 bg-white/[.02] py-20"><Container><div className="grid gap-8 lg:grid-cols-2"><div><SectionHeading eyebrow="Workflow examples" title="Technology shaped around real work" description="We start with the journey that needs to work, then select an appropriate technical approach."/><div className="mt-8"><Checklist items={solution.workflows}/></div></div><div className="card"><p className="text-sm font-semibold text-cyan-100">What a stronger system can create</p><div className="mt-6"><Checklist items={solution.benefits}/></div></div></div></Container></section>
    {(relatedProducts.length > 0 || relatedIndustries.length > 0) && <section className="py-20"><Container><SectionHeading eyebrow="Connected expertise" title="See where this solution applies"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{relatedProducts.map((x) => <CardLink key={x.id} href={`/products/${x.slug}`} eyebrow={x.status} title={x.name} description={x.summary}/>) }{relatedIndustries.map((x) => <CardLink key={x.slug} href={`/industries/${x.slug}`} eyebrow="Industry" title={x.name} description={x.summary}/>)}</div></Container></section>}
    <CTA />
  </>;
}

export function IndustryPage({ industry }: { industry: Industry }) {
  const relatedProducts = (industry.productIds ?? []).map(productById).filter(Boolean) as Product[];
  const relatedWork = (industry.implementationIds ?? []).map(implementationById).filter(Boolean) as Implementation[];
  return <><PageIntro eyebrow="Industry technology" title={industry.name} description={industry.summary} breadcrumbs={[{label:"Industries",href:"/industries"},{label:industry.name}]} actions={<ButtonLink href="/business-technology-review">Review your technology needs</ButtonLink>}/>
    <section className="py-20"><Container><div className="grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Common pressure points" title="Where operations start to lose momentum"/><div className="mt-8"><Checklist items={industry.problems}/></div></div><div className="card"><p className="text-sm font-semibold text-cyan-100">Relevant VertexIQ capabilities</p><div className="mt-6"><Checklist items={industry.capabilities}/></div></div></div></Container></section>
    <section className="border-y border-white/8 bg-white/[.02] py-20"><Container><SectionHeading eyebrow="A connected approach" title="Relevant solutions, technology and work"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{industry.solutionSlugs.map(solutionBySlug).filter(Boolean).map((x) => <CardLink key={x!.slug} href={`/solutions/${x!.slug}`} eyebrow="Solution" title={x!.name} description={x!.summary}/>)}{relatedProducts.map((x) => <CardLink key={x.id} href={`/products/${x.slug}`} eyebrow={x.status} title={x.name} description={x.summary}/>)}{relatedWork.map((x) => <CardLink key={x.id} href={`/our-work/${x.slug}`} eyebrow="Client implementation" title={x.client} description={x.summary}/>)}</div></Container></section><CTA title={`Discuss technology for ${industry.name.toLowerCase()}.`}/></>;
}

export function ProductPage({ product }: { product: Product }) {
  const relatedWork = product.implementationIds.map(implementationById).filter(Boolean) as Implementation[];
  const value = productValue[product.id];
  const secondaryHref = product.id==="fields-os" ? "/our-work/ecoclean-ghana" : "/business-technology-review";
  const jsonLd = { "@context":"https://schema.org", "@type":"SoftwareApplication", name:product.name, description:product.summary, applicationCategory:"BusinessApplication", operatingSystem:"Web", url:`https://www.vertexiqsystems.com/products/${product.slug}`, author:{"@type":"Organization",name:"VertexIQ Systems"} };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/>{product.id==="motix"?<MotixHero product={product}/>:<PageIntro eyebrow={product.sector} title={product.name} description={product.positioning} breadcrumbs={[{label:"Products",href:"/products"},{label:product.name}]} actions={<><ButtonLink href="/contact">{product.primaryCta}</ButtonLink><ButtonLink href={secondaryHref} variant="secondary">{product.secondaryCta}</ButtonLink></>}/>}
    <section className="py-16"><Container><div className={`grid gap-8 ${product.id==="motix"?"lg:grid-cols-[1.15fr_.85fr]":"lg:grid-cols-[.72fr_1.28fr]"} lg:items-stretch`}><div className="card"><StatusBadge label={product.status} tone={product.statusTone}/><p className="mt-6 text-xl font-semibold text-white">{product.id==="motix"?"The complete garage management platform":product.strapline}</p><p className="mt-4 leading-7 text-slate-400">{value.promise}</p><dl className="mt-7 grid gap-5 border-t border-white/8 pt-6 text-sm"><Fact label="Ownership" value={product.ownership}/><Fact label="Availability" value={product.availability}/><Fact label="Sector" value={product.sector}/>{product.regions && <Fact label="Region" value={product.regions.join(", ")}/>}</dl></div>{product.id==="motix"?<div className="card"><p className="eyebrow">Connected garage value</p><h2 className="mt-4 text-2xl font-semibold text-white">One operational line from booking to handover</h2><div className="mt-6"><Checklist items={["Bring customers, vehicles and bookings together","Move work through reception, workshop and review","Connect job cards to invoicing, payments and handover","Give teams clearer workshop and MOT visibility"]}/></div></div>:<ProductVisual eyebrow={product.status} title={product.strapline} description={product.summary} items={product.capabilities.slice(0,4)}/>}</div></Container></section>
    {product.id==="motix"&&<><MotixFrontDoorStory/><MotixEvidence/><MotixCrossDeviceStory/></>}
    {product.id==="xmor-care-os"&&<section className="border-y border-amber-300/15 bg-amber-300/[.035] py-6"><Container><p className="text-sm leading-7 text-amber-100"><strong>Development status:</strong> XMOR Care OS is in advanced development and is not presented as commercially live. Capability language describes the current architecture direction, not a purchase-ready service.</p></Container></section>}
    <section className="border-y border-white/8 bg-white/[.02] py-20"><Container><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><SectionHeading eyebrow="Operational value" title={value.title} description={value.description}/><div className="mt-8"><Checklist items={value.outcomes}/></div></div><div className="card"><p className="text-sm font-semibold text-cyan-100">Verified platform scope</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Checklist items={product.capabilities}/></div></div></div></Container></section>
    {relatedWork.length > 0 && <section className="py-20"><Container><SectionHeading eyebrow="In practice" title={product.id==="motix"?"MOTIX in real operations":"Connected client implementation"} description={product.id==="motix"?"ATECH Services UK is a real UK client implementation connecting the public website, bookings, customers and vehicles with workshop, technician, job-card, invoice, payment and MOT workflows.":undefined}/><div className="mt-10 grid gap-5 md:grid-cols-2">{relatedWork.map((x) => <CardLink key={x.id} href={`/our-work/${x.slug}`} eyebrow={x.sector} title={x.client} description={x.summary}/>)}</div></Container></section>}
    <CTA title={value.ctaTitle} description={value.ctaDescription} primaryLabel={product.primaryCta} primaryHref="/contact"/></>;
}

export function ImplementationPage({ implementation }: { implementation: Implementation }) {
  const product = productById(implementation.productId)!;
  const industry = industries.find((x) => x.slug === implementation.industrySlug)!;
  const jsonLd = { "@context":"https://schema.org", "@type":"CreativeWork", name:`${implementation.client} technology implementation`, description:implementation.summary, url:`https://www.vertexiqsystems.com/our-work/${implementation.slug}`, creator:{"@type":"Organization",name:"VertexIQ Systems"}, about:[{"@type":"Organization",name:implementation.client},{"@type":"SoftwareApplication",name:product.name}] };
  const map = implementationMaps[implementation.id];
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/><PageIntro eyebrow="Client implementation" title={implementation.client} description={implementation.title} breadcrumbs={[{label:"Our Work",href:"/our-work"},{label:implementation.client}]} actions={<><ButtonLink href={`/products/${product.slug}`}>Explore {product.name}</ButtonLink><ButtonLink href="/contact" variant="secondary">{map.cta}</ButtonLink></>}/>
    <section className="py-16"><Container><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><ProductVisual eyebrow="Implementation scope" title={map.title} description={map.description} items={implementation.built.slice(0,4)}/><div className="card"><p className="eyebrow">Connected technology approach</p><Link href={`/products/${product.slug}`} className="mt-4 block text-3xl font-semibold text-white hover:text-cyan-100">{product.name}</Link><p className="mt-4 leading-7 text-slate-400">{implementation.summary}</p><dl className="mt-7 grid gap-5 border-t border-white/8 pt-6 text-sm"><Fact label="Client" value={implementation.client}/><Fact label="Sector" value={implementation.sector}/><Fact label="Connected product" value={product.name}/></dl><Link className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-cyan-200" href={`/industries/${industry.slug}`}>{industry.name}<ArrowRight aria-hidden="true" size={15}/></Link></div></div></Container></section>
    <section className="border-y border-white/8 bg-white/[.02] py-20"><Container><div className="grid gap-10 lg:grid-cols-2"><div><SectionHeading eyebrow="The challenge" title={implementation.challenge}/><p className="lead mt-8">{implementation.approach}</p></div><div className="card"><p className="text-sm font-semibold text-cyan-100">What VertexIQ built</p><div className="mt-6"><Checklist items={implementation.built}/></div></div></div></Container></section>
    <section className="py-20"><Container><SectionHeading eyebrow="Capability map" title={map.title} description={map.description}/><div className="mt-10 grid gap-5 md:grid-cols-3">{map.groups.map(group=><div className="card" key={group.title}><h2 className="text-lg font-semibold text-white">{group.title}</h2><div className="mt-5"><Checklist items={group.items}/></div></div>)}</div></Container></section>
    <CTA title={map.ctaTitle} primaryLabel={map.cta} primaryHref="/contact"/></>;
}

function InfoBlock({ title, items }: { title: string; items: string[] }) { return <div className="card"><p className="text-sm font-semibold text-white">{title}</p><div className="mt-5"><Checklist items={items}/></div></div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-100">{value}</dd></div>; }

function MotixHero({product}:{product:Product}){const capabilityLine=["Bookings","Customers","Vehicles","Reception","Workshop","Job Cards","Invoicing","Payments","MOT Intelligence"];return <section className="motix-hero"><Container className="relative py-8 sm:py-10 lg:py-14"><Breadcrumbs items={[{label:"Products",href:"/products"},{label:product.name}]}/><div className="grid gap-8 lg:grid-cols-[.92fr_1.08fr] lg:items-center"><div><div className="flex flex-wrap items-center gap-3"><StatusBadge label="Live" tone="live"/><span className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">MOTIX™ by VertexIQ Systems</span></div><h1 className="sr-only">MOTIX™</h1><div className="mt-6 max-w-xl overflow-hidden rounded-2xl border border-blue-400/20 bg-black p-2"><Image src="/products/motix/motix-logo-master.png" alt="MOTIX — Manage. Service. Grow. The complete garage management platform." width={1536} height={1024} priority sizes="(max-width: 1024px) 100vw, 46vw" className="h-auto w-full object-contain"/></div></div><div><p className="text-xs font-bold uppercase tracking-[.22em] text-blue-300">Manage. Service. Grow.</p><h2 className="mt-5 text-4xl font-semibold leading-tight tracking-[-.035em] text-white sm:text-5xl">Run your garage from one connected system.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">The complete garage management platform for connected customer, vehicle, reception, workshop and payment workflows.</p><ul className="mt-6 flex flex-wrap gap-x-3 gap-y-2 text-sm text-slate-400" aria-label="MOTIX capability summary">{capabilityLine.map((item,index)=><li key={item} className="flex items-center gap-3">{index>0&&<span aria-hidden="true" className="text-blue-400">•</span>}{item}</li>)}</ul><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/contact">Request a MOTIX Demo</ButtonLink><ButtonLink href="#live-workshop" variant="secondary">See MOTIX in Action</ButtonLink></div></div></div></Container></section>}

function MotixEvidence(){const stages=["Waiting","Assigned","In Workshop","Paused / Parts","Quality Check","Reception Review","Ready / Collected"];return <section id="live-workshop" className="scroll-mt-24 border-y border-blue-400/15 bg-blue-500/[.025] py-20"><Container><div className="grid gap-10 xl:grid-cols-[.62fr_1.38fr] xl:items-start"><div><SectionHeading eyebrow="MOTIX in action" title="Live Workshop" description="Monitor every job from assignment through reception review and collection."/><ol className="motix-workflow mt-8" aria-label="MOTIX Live Workshop stages">{stages.map((stage,index)=><li key={stage}><span className="sr-only">Stage {index+1}: </span>{stage}</li>)}</ol><p className="mt-6 text-sm leading-6 text-slate-400">See workshop demand, ownership and progress in one operational view — from the waiting queue through quality checks, reception review and collection.</p><Link href="/products/motix/demo/workshop" className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-cyan-200">Open full demo view<ArrowRight aria-hidden="true" size={15}/></Link></div><div className="overflow-hidden rounded-2xl border border-blue-400/20 bg-[#03060b] p-2 shadow-2xl shadow-blue-950/20 sm:p-3"><div className="mb-2 flex items-center gap-1.5 px-1" aria-hidden="true"><span className="size-2 rounded-full bg-slate-700"/><span className="size-2 rounded-full bg-slate-700"/><span className="size-2 rounded-full bg-blue-600"/></div><MotixLiveWorkshopDemo/></div></div></Container></section>}

const productValue: Record<string,{promise:string;title:string;description:string;outcomes:string[];ctaTitle:string;ctaDescription:string}> = {
  motix:{promise:"Give garage teams a clearer line of sight from the first booking to completed work and customer handover.",title:"Make the garage easier to run — and easier to use",description:"MOTIX is designed around the practical work of customers, vehicles, reception, workshop teams and payment.",outcomes:["Easier booking and reception journeys","Clearer customer and vehicle records","Workshop work organised around job cards","A more connected path to invoice, payment and handover"],ctaTitle:"Ready to discuss a more connected garage operation?",ctaDescription:"Request a MOTIX conversation around your current booking, workshop and customer workflows."},
  "fields-os":{promise:"Bring customer registration, field delivery and service management into a more structured operational model.",title:"Coordinate services beyond the office",description:"Fields OS supports field-service organisations where customer, zone and operational information needs to stay connected.",outcomes:["Clearer customer registration","More structured service workflows","Better connection between field and office work","A practical foundation for service and payment management"],ctaTitle:"Discuss the field operation you need to connect.",ctaDescription:"Start with the customers, services, zones and operational hand-offs that are difficult to coordinate today."},
  medlink:{promise:"Support clearer digital healthcare journeys for appointments, consultations, clinics and doctors in Ghana.",title:"Healthcare workflows with clarity and restraint",description:"MedLink is a VertexIQ-owned platform starting operations in Ghana, designed around accessible consultation and administration journeys.",outcomes:["Structured appointment and consultation states","Clearer clinic and doctor administration","Support for voice and video consultation options","Controlled handling of fees, availability and payment state"],ctaTitle:"Discuss MedLink or healthcare technology in Ghana.",ctaDescription:"Talk to VertexIQ about the platform direction or a healthcare workflow that needs a careful digital approach."},
  "xmor-care-os":{promise:"Engineer a modular operating foundation for modern care and support organisations without overstating commercial availability.",title:"Care-sector depth, currently in advanced development",description:"XMOR Care OS is being shaped around connected care operations, workforce processes, finance and compliance-conscious architecture.",outcomes:["A modular approach to care operations","Connected service-user and workforce workflow direction","Finance capability considered within the operating model","Multi-tenant SaaS architecture direction"],ctaTitle:"Register interest in the direction of XMOR Care OS.",ctaDescription:"Discuss care technology, the operational problem you are solving and whether the platform direction is relevant."},
};

const implementationMaps: Record<string,{title:string;description:string;cta:string;ctaTitle:string;groups:{title:string;items:string[]}[]}> = {
  atech:{title:"From customer intent to completed workshop work",description:"The implementation connects the public customer journey with the operating workflows used by an automotive business.",cta:"Discuss technology for your garage",ctaTitle:"Could your garage benefit from a more connected operating system?",groups:[{title:"Customer journey",items:["Public website","Bookings","Customer and vehicle records"]},{title:"Workshop operation",items:["Reception and walk-ins","Quotes and job cards","Workshop and technician workflows"]},{title:"Completion and visibility",items:["Invoices and payments","Customer handover","MOT intelligence and reporting"]}]},
  ecoclean:{title:"A structured model for customer and field-service delivery",description:"The implementation connects customer-facing digital services with the workflows used to coordinate services across the field.",cta:"Discuss field-service technology",ctaTitle:"Discuss a clearer operating model for your field-service business.",groups:[{title:"Customer platform",items:["Customer registration","Customer-facing digital services"]},{title:"Service workflows",items:["Structured service journeys","Payment and service-management capability"]},{title:"Field operation",items:["Zone-based operations","Operational tracking and coordination"]}]},
};
