import Link from "next/link";
import FormSubmitButton from "./FormSubmitButton";

const endpoint="https://formsubmit.co/b7ead2955da23d14f0e6002b8fbaa5e9";
const interests=["Websites & Digital Growth","CRM & Business Systems","Custom Software","SaaS Development","Mobile Applications","AI & Automation","Systems Integration","MOTIX demo","Fields OS","MedLink","XMOR Care OS","Not sure yet"];

export default function EnquiryForm({source="contact",review=false}:{source?:string;review?:boolean}){
  const privacyId=`${source}-privacy-note`;
  return <form action={endpoint} method="POST" className="grid gap-7" aria-describedby={privacyId}>
    <input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_template" value="table"/><input type="hidden" name="_subject" value={review?"New VertexIQ Business Technology Review":"New VertexIQ Enquiry"}/><input type="hidden" name="_next" value="https://www.vertexiqsystems.com/thank-you"/><input type="hidden" name="enquirySource" value={source}/>
    <fieldset className="grid gap-5"><legend className="mb-1 text-sm font-bold uppercase tracking-[.14em] text-cyan-100">About you</legend><div className="grid gap-5 sm:grid-cols-2"><Field id={`${source}-name`} label="Full name" required><input className="form-control" id={`${source}-name`} name="name" autoComplete="name" minLength={2} maxLength={120} required/></Field><Field id={`${source}-company`} label="Company"><input className="form-control" id={`${source}-company`} name="company" autoComplete="organization" maxLength={160}/></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field id={`${source}-email`} label="Work email" required><input className="form-control" id={`${source}-email`} name="email" type="email" autoComplete="email" maxLength={254} required/></Field><Field id={`${source}-phone`} label="Telephone / WhatsApp"><input className="form-control" id={`${source}-phone`} name="telephone" type="tel" inputMode="tel" autoComplete="tel" maxLength={40}/></Field></div></fieldset>
    <fieldset className="grid gap-5 border-t border-white/8 pt-7"><legend className="mb-1 text-sm font-bold uppercase tracking-[.14em] text-cyan-100">About the business need</legend><div className="grid gap-5 sm:grid-cols-2"><Field id={`${source}-sector`} label="Sector"><input className="form-control" id={`${source}-sector`} name="sector" placeholder="For example, automotive" maxLength={120}/></Field><Field id={`${source}-interest`} label="What are you interested in?" required><select className="form-control" id={`${source}-interest`} name="interest" required defaultValue=""><option value="" disabled>Select an option</option>{interests.map(x=><option key={x}>{x}</option>)}</select></Field></div>
    {review&&<fieldset className="rounded-xl border border-white/10 p-5"><legend className="px-2 text-sm font-semibold text-white">Where is the biggest pressure? <span className="font-normal text-slate-400">Select any that apply</span></legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{["Customer acquisition","Enquiries or bookings","Customer management","Manual administration","Staff or operations","Payments or invoicing","Disconnected systems","A new software idea"].map(x=><label key={x} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-lg px-2 text-sm text-slate-300 hover:bg-white/[.03]"><input type="checkbox" name="problemAreas" value={x} className="h-4 w-4 shrink-0 accent-cyan-300"/>{x}</label>)}</div></fieldset>}
    <Field id={`${source}-message`} label={review?"What would you like to improve?":"Tell us about the challenge"} required help={review?"Explain it in business terms — you do not need to know the technical solution.":"A short description of the current problem and what better would look like is enough."}><textarea className="form-control min-h-36 resize-y" id={`${source}-message`} name="message" minLength={20} maxLength={3000} required/></Field></fieldset>
    <div className="rounded-xl border border-white/8 bg-white/[.025] p-4"><p className="text-sm font-semibold text-white">What happens after you submit</p><p className="mt-2 text-sm leading-6 text-slate-400">VertexIQ will review the context and use the contact details provided to respond with an appropriate next step. This form does not create an account or save a draft.</p></div>
    <p id={privacyId} className="text-sm leading-6 text-slate-400">Your details are submitted to our current form-delivery provider so VertexIQ can respond to this enquiry. Do not include sensitive information. Read our <Link className="text-cyan-200 underline underline-offset-4" href="/privacy">privacy information</Link>.</p>
    <FormSubmitButton label={review?"Request my free technology review":"Send enquiry to VertexIQ"}/>
  </form>;
}

function Field({id,label,required,help,children}:{id:string;label:string;required?:boolean;help?:string;children:React.ReactNode}){return <div><label className="form-label" htmlFor={id}>{label}{required&&<><span aria-hidden="true" className="text-cyan-200"> *</span><span className="sr-only"> (required)</span></>}</label>{children}{help&&<p className="form-help">{help}</p>}</div>}
