import Link from "next/link";
import { ArrowDown, ArrowRight, Globe2, Laptop, Monitor, Smartphone, Wrench } from "lucide-react";
import { Container, SectionHeading } from "./ui";

const journey=["Find garage","Visit website","Request booking","Reception review","Customer + vehicle","Job card","Workshop","Technician","Reception review","Invoice / payment","Handover"];
const models=[
  {label:"Need a new website",title:"MOTIX-connected website",copy:"A professionally branded garage website designed around your business and connected customer journey."},
  {label:"Already have a good website",title:"Existing website connection",copy:"Keep the website that already works while planning an appropriate, secure connection into the garage’s MOTIX environment."},
  {label:"Website needs attention",title:"Modernisation + MOTIX",copy:"Modernise an ageing customer experience and connect booking intent to the operational workflow behind it."},
];

export function MotixFrontDoorStory(){return <>
  <section className="border-y border-white/8 bg-white/[.02] py-20"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><SectionHeading eyebrow="Connected garage platform" title="From your website to your workshop." description="Your website becomes the digital front door to MOTIX — connecting customer booking intent with the garage operation behind it."/><p className="mt-6 text-sm leading-7 text-slate-400">Already have a good website? Keep it, subject to an appropriate secure integration. Need a new one? VertexIQ can create a professionally branded MOTIX-connected garage website. In every model, a public booking remains a request that reception reviews before it becomes trusted operational work.</p><Link href="/products/motix/demo/garage" className="mt-7 inline-flex min-h-11 items-center gap-2 rounded-xl bg-cyan-300 px-5 text-sm font-bold text-slate-950">Explore the customer journey<ArrowRight size={16}/></Link></div><div className="grid gap-4 md:grid-cols-3">{models.map((model,index)=><article key={model.title} className="rounded-2xl border border-white/10 bg-[#080d18] p-5"><span className="grid size-9 place-items-center rounded-xl bg-blue-500/10 text-sm font-black text-blue-200">{index+1}</span><p className="mt-5 text-[10px] font-bold uppercase tracking-[.16em] text-blue-300">{model.label}</p><h3 className="mt-2 text-lg font-bold text-white">{model.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{model.copy}</p></article>)}</div></div></Container></section>
  <section className="py-20"><Container><SectionHeading eyebrow="One connected journey" title="Customer intent becomes controlled garage work" description="A clear line from discovery and booking through reception, workshop, technician activity and customer handover."/><ol className="mt-10 grid gap-2 sm:grid-cols-2 lg:grid-cols-6" aria-label="MOTIX connected customer journey">{journey.map((step,index)=><li key={`${step}-${index}`} className="relative flex min-h-20 items-center gap-3 rounded-xl border border-blue-400/15 bg-blue-500/[.04] p-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-blue-600 text-[10px] font-bold text-white">{index+1}</span><span className="text-xs font-bold text-slate-200">{step}</span>{index<journey.length-1&&<ArrowDown aria-hidden="true" className="absolute -bottom-2.5 left-1/2 z-10 rounded-full bg-[#040714] p-1 text-blue-400 lg:-right-2.5 lg:bottom-auto lg:left-auto lg:top-1/2 lg:-rotate-90" size={20}/>}</li>)}</ol><div className="mt-8 grid gap-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.035] p-5 sm:grid-cols-[auto_1fr] sm:items-center"><Globe2 className="text-amber-200"/><p className="text-sm leading-6 text-amber-50"><strong>Trust boundary:</strong> the public website creates a booking request, not an unrestricted job, invoice or workshop record. The garage retains operational authority.</p></div></Container></section>
  </>}

export function MotixCrossDeviceStory(){return <>
  <section className="border-y border-blue-400/15 bg-[radial-gradient(circle_at_75%_20%,rgba(37,99,235,.13),transparent_30%),#03070d] py-20"><Container><div className="grid gap-12 lg:grid-cols-[.78fr_1.22fr] lg:items-center"><div><p className="eyebrow">Desktop + mobile · One connected garage</p><h2 className="mt-5 text-4xl font-bold leading-tight tracking-tight text-white sm:text-5xl">Run the garage from the desk, the workshop or on the move.</h2><p className="mt-6 max-w-xl leading-7 text-slate-300">Reception, management and other authorised garage users can work through appropriate desktop and mobile experiences underpinned by the same connected MOTIX operation.</p><div className="mt-7 flex flex-wrap gap-2 text-xs text-slate-300">{["Dashboard","Bookings","Customers","Vehicles","Reception","Job Cards","Workshop","Invoices","MOT intelligence","Global Search"].map(item=><span key={item} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2">{item}</span>)}</div></div><div className="relative min-h-[30rem]"><div className="absolute inset-x-0 top-3 overflow-hidden rounded-2xl border border-white/10 bg-[#07101d] shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><span className="text-xs font-black tracking-widest text-white">MOTIX™</span><Monitor size={16} className="text-blue-300"/></div><div className="grid grid-cols-[7rem_1fr] p-4"><div className="grid content-start gap-2 border-r border-white/10 pr-3">{["Dashboard","Bookings","Customers","Vehicles","Workshop"].map(item=><span key={item} className="rounded-md bg-white/[.04] px-2 py-2 text-[9px] text-slate-400">{item}</span>)}</div><div className="grid grid-cols-2 gap-3 pl-4"><div className="h-20 rounded-xl bg-blue-500/10"/><div className="h-20 rounded-xl bg-white/[.04]"/><div className="col-span-2 h-40 rounded-xl border border-white/[.06] bg-black/20"/></div></div></div><div className="absolute bottom-0 right-2 w-48 overflow-hidden rounded-[2rem] border-[7px] border-slate-800 bg-[#060b14] shadow-2xl sm:right-8 sm:w-56"><div className="mx-auto mt-2 h-1 w-14 rounded-full bg-slate-700"/><div className="p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-black tracking-wider">MOTIX™</span><Smartphone size={13} className="text-blue-300"/></div><p className="mt-5 text-sm font-bold">Garage operations</p><div className="mt-3 grid gap-2">{["Bookings","Vehicle Reception","Workshop","Global Search"].map(item=><span key={item} className="rounded-lg border border-white/[.07] bg-white/[.03] p-2 text-[9px] text-slate-300">{item}</span>)}</div></div></div><Laptop className="absolute bottom-4 left-4 text-blue-300/50" size={25}/></div></div></Container></section>
  <section className="py-20"><Container><div className="grid gap-10 lg:grid-cols-[1fr_.85fr] lg:items-center"><div><SectionHeading eyebrow="Built for the workshop floor" title="MOTIX Technician™" description="A dedicated mobile experience that keeps assigned work and evidence capture close to the technician doing the job."/><div className="mt-7 grid gap-4 sm:grid-cols-3">{[["Assigned jobs","See allocated workshop work"],["Media upload","Capture visual job evidence"],["Voice dictation","Record job observations efficiently"]].map(([title,copy])=><div key={title} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><Wrench size={17} className="text-blue-300"/><h3 className="mt-3 text-sm font-bold text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{copy}</p></div>)}</div></div><div className="rounded-2xl border border-blue-400/15 bg-blue-500/[.04] p-6"><p className="text-xs font-bold uppercase tracking-[.17em] text-blue-300">Technician experience</p><p className="mt-4 text-2xl font-bold text-white">Focused tools at the point of work.</p><p className="mt-4 text-sm leading-6 text-slate-400">Explore a safe local demonstration of assigned jobs, sample media capture and voice-note preview.</p><Link href="/products/motix/demo/technician" className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-cyan-200">See the Technician App<ArrowRight size={16}/></Link></div></div></Container></section>
  </>}
