import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import { implementations, productById } from "@/lib/content";
import { createMetadata } from "@/lib/seo";
import { Container, CTA, PageIntro, ProductVisual, SectionHeading } from "@/components/ui";
export const metadata: Metadata=createMetadata("Our Work","Verified VertexIQ client implementations for ATECH Services UK and EcoClean Ghana.","/our-work");
const locations:Record<string,string>={atech:"United Kingdom",ecoclean:"Ghana"};
export default function Page(){return <><PageIntro eyebrow="Our Work" title="Real technology in real operations." description="Verified client implementations showing how VertexIQ connects customer-facing digital services with the systems used to run the work."/><section className="py-20"><Container><SectionHeading eyebrow="Client implementations" title="Practical depth without invented results" description="These previews show the operational scope, product connection and delivery context for each client."/><div className="mt-12 grid gap-8">{implementations.map((item,index)=>{const product=productById(item.productId)!;return <article key={item.id} className="grid overflow-hidden rounded-3xl border border-white/10 bg-white/[.025] lg:grid-cols-[.9fr_1.1fr]"><ProductVisual compact eyebrow="Implementation scope" title={item.title} description={item.challenge} items={item.built.slice(0,4)}/><div className={`p-6 sm:p-8 lg:p-10 ${index%2===1?"lg:order-first":""}`}><div className="flex flex-wrap gap-3 text-xs font-bold uppercase tracking-[.14em] text-slate-400"><span>{item.sector}</span><span className="inline-flex items-center gap-1.5"><MapPin aria-hidden="true" size={13}/>{locations[item.id]}</span></div><h2 className="mt-5 text-3xl font-semibold text-white">{item.client}</h2><p className="mt-2 text-sm font-semibold text-cyan-200">Connected to {product.name}</p><p className="mt-5 leading-7 text-slate-400">{item.summary}</p><ul className="mt-6 flex flex-wrap gap-2" aria-label="Implementation scope">{item.built.map(scope=><li key={scope} className="rounded-full border border-white/8 px-3 py-1.5 text-xs text-slate-300">{scope}</li>)}</ul><Link href={`/our-work/${item.slug}`} className="mt-8 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-cyan-200">View {item.client} implementation<ArrowRight aria-hidden="true" size={16}/></Link></div></article>})}</div></Container></section><CTA title="See what connected technology could improve in your operation."/></>}
