import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { products } from "@/lib/content";
import { createMetadata } from "@/lib/seo";
import { Container, CTA, PageIntro, ProductVisual, SectionHeading, StatusBadge } from "@/components/ui";
import MotixBrandMedia from "@/components/MotixBrandMedia";

export const metadata: Metadata=createMetadata("Products","Explore MOTIX, Fields OS, MedLink and XMOR Care OS: technology products and platforms by VertexIQ Systems.","/products");

export default function Page(){return <><PageIntro eyebrow="Technology by VertexIQ" title="Products built from real operational problems." description="Our platforms apply product engineering to the workflows of automotive, field-service, healthcare and care organisations."/><section className="py-20"><Container><SectionHeading eyebrow="Product portfolio" title="Different sectors. One practical engineering approach." description="Every product is shown with its current status, ownership and availability."/><div className="mt-12 grid gap-8">{products.map((product,index)=><article key={product.id} className="grid overflow-hidden rounded-3xl border border-white/10 bg-white/[.025] lg:grid-cols-2"><div className={`p-6 sm:p-8 lg:p-10 ${index%2===1?"lg:order-2":""}`}><div className="flex flex-wrap items-center gap-3"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">{product.sector}</p><StatusBadge label={product.status} tone={product.statusTone}/></div><h2 className="mt-5 text-3xl font-semibold tracking-tight text-white sm:text-4xl">{product.name}</h2>{product.id==="motix"&&<p className="mt-2 text-xs font-bold uppercase tracking-[.2em] text-blue-300">Manage. Service. Grow.</p>}<p className="mt-3 text-lg font-medium text-cyan-100">{product.strapline}</p><p className="mt-5 max-w-xl leading-7 text-slate-400">{product.summary}</p><div className="mt-6 flex flex-wrap gap-2">{product.capabilities.slice(0,3).map(item=><span key={item} className="rounded-full border border-white/8 bg-white/[.035] px-3 py-1.5 text-xs text-slate-300">{item}</span>)}</div><Link href={`/products/${product.slug}`} className="mt-8 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-cyan-200">Explore {product.name}<ArrowRight aria-hidden="true" size={16}/></Link></div>{product.id==="motix"?<MotixBrandMedia compact/>:<ProductVisual compact eyebrow={product.status} title={product.strapline} description={product.summary} items={product.capabilities.slice(0,4)}/>}</article>)}</div></Container></section><CTA title="Which product or platform direction fits your operation?" description="Talk to VertexIQ about the workflow, sector and practical result you need."/></>}
